[package]
name = "predicate-logic-visualizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
id_tree = "1.8.0"
id_tree_layout = "2.0.4"
console_error_panic_hook = "0.1.7"
