on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Publish to Cloudflare Pages
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: jetli/wasm-pack-action@v0.4.0

            - name: Build frontend
              run: |
                  wasm-pack build --target web --out-dir interactive/pkg
                  cd interactive
                  pnpm install
                  pnpm run build

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: predicate-logic-visualizer
                  directory: interactive/dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
